# Generated by Django 4.0.3 on 2022-03-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do estabelecimento')),
                ('cnes', models.CharField(max_length=11, verbose_name='Código CNES')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
            ],
        ),
    ]
