# Generated by Django 4.0.3 on 2022-03-16 21:15

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_atend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome grupo atendimento')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visibilidade')),
                ('fase', models.CharField(default='000', max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='data de criacao')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='nome completo')),
                ('cpf', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('covid_recente', models.BooleanField(verbose_name='teve covid recentemente')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('grupo_atendimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.grupo_atend', verbose_name='grupo atendimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
