# Generated by Django 4.0.3 on 2022-03-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo_atend',
            old_name='date_added',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='grupo_atend',
            old_name='is_visible',
            new_name='visivel',
        ),
        migrations.AddField(
            model_name='grupo_atend',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo_atend',
            name='codigo_si_pni',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='grupo_atend',
            name='grupo_pai',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='grupo_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.grupo_atend', verbose_name='grupo atendimento'),
        ),
        migrations.AlterField(
            model_name='grupo_atend',
            name='fase',
            field=models.CharField(blank=True, default='000', max_length=15, null=True),
        ),
    ]
