# Generated by Django 4.0.3 on 2022-03-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_date_added_grupo_atend_criado_em_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupo_atend',
            new_name='grupos_atendimento',
        ),
    ]
