# Generated by Django 4.0.3 on 2022-03-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_grupos_atendimento_visivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos_atendimento',
            name='visivel',
            field=models.CharField(blank=True, default='true', max_length=5, null=True, verbose_name='visibilidade'),
        ),
    ]
